/**
 * Canonical editor renderer: offline CodeMirror 6 inside
 * `react-native-webview`.
 *
 * - The CodeMirror bundle (`src/editor/cmBundle.ts`, generated by
 *   `npm run vendor:editor`) is inlined into the HTML document. No CDN,
 *   no remote loading, no file access.
 * - The document is built ONCE per mount (`initialDoc` + initial grammar
 *   + initial theme). Everything after that — document swaps, grammar
 *   changes, live theme updates, history, search — flows through
 *   `postInbound()` so the WebView (and undo history) is never reloaded.
 * - Text changes and cursor movement bypass React state on the way out
 *   (`onMessage`) so typing stays responsive; the parent mirrors text
 *   into its own store.
 */
import { useEffect, useImperativeHandle, useMemo, useRef } from "react";
import { StyleSheet, Text, View } from "react-native";
import { WebView, type WebViewMessageEvent } from "react-native-webview";

import { CM_BUNDLE_JS } from "@/editor/cmBundle";
import { buildEditorDocument } from "@/editor/editorDocument";
import type {
  EditorTheme,
  EditorWebViewInbound,
  EditorWebViewOutbound,
} from "@/editor/editorTypes";

export interface CodeMirrorWebViewProps {
  theme: EditorTheme;
  grammarKey: string | null;
  initialDoc: string;
  onMessage?: (message: EditorWebViewOutbound) => void;
  onReady?: () => void;
  /** Stable document identity for the intel engine; null disables it. */
  uri?: string | null;
  /** Master switch for the in-WebView semantic engine. */
  intelEnabled?: boolean;
}

export interface CodeMirrorWebViewRef {
  postInbound(message: EditorWebViewInbound): void;
}

export function CodeMirrorWebView({
  theme,
  grammarKey,
  initialDoc,
  onMessage,
  onReady,
  uri = null,
  intelEnabled = false,
  ref,
}: CodeMirrorWebViewProps & {
  ref?: React.Ref<CodeMirrorWebViewRef>;
}): React.JSX.Element {
  const webViewRef = useRef<WebView>(null);
  const messageRef = useRef(onMessage);
  messageRef.current = onMessage;
  const readyRef = useRef(onReady);
  readyRef.current = onReady;

  useImperativeHandle(
    ref,
    () => ({
      postInbound(message: EditorWebViewInbound): void {
        webViewRef.current?.injectJavaScript(
          `window.__ajiroEditorInbox(${JSON.stringify(message)});true;`,
        );
      },
    }),
    [],
  );

  const html = useMemo(() => {
    if (!CM_BUNDLE_JS) {
      return null;
    }
    return buildEditorDocument({
      theme,
      grammarKey,
      doc: initialDoc,
      uri,
      intelEnabled,
    });
    // Built once: theme/grammar/doc updates go through postInbound so the
    // editor (and its undo history) is never reloaded for visual updates.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleMessage = (event: WebViewMessageEvent): void => {
    let message: EditorWebViewOutbound;
    try {
      message = JSON.parse(event.nativeEvent.data) as EditorWebViewOutbound;
    } catch {
      return;
    }
    if (message.type === "ready") {
      readyRef.current?.();
    }
    messageRef.current?.(message);
  };

  useEffect(() => {
    return () => {
      webViewRef.current = null;
    };
  }, []);

  if (!html) {
    return (
      <View
        style={[
          styles.container,
          styles.missing,
          { backgroundColor: theme.background },
        ]}
      >
        <Text style={[styles.missingText, { color: theme.foreground }]}>
          Editor bundle missing. Run `npm run vendor:editor` after `npm
          install`, then rebuild.
        </Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <WebView
        ref={webViewRef}
        originWhitelist={["*"]}
        source={{ html, baseUrl: "about:blank" }}
        style={styles.webview}
        containerStyle={styles.webview}
        javaScriptEnabled
        domStorageEnabled={false}
        allowFileAccess={false}
        allowUniversalAccessFromFileURLs={false}
        mixedContentMode="never"
        cacheEnabled={false}
        onMessage={handleMessage}
        showsVerticalScrollIndicator={false}
        showsHorizontalScrollIndicator={false}
        keyboardDisplayRequiresUserAction={false}
        hideKeyboardAccessoryView={false}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  webview: { flex: 1, backgroundColor: "transparent" },
  missing: { alignItems: "center", justifyContent: "center", padding: 24 },
  missingText: { fontSize: 13, fontFamily: "monospace", textAlign: "center" },
});
