/**
 * Extension → CodeMirror grammar table (pure, unit-tested).
 *
 * Keys resolve inside the vendored offline bundle (`cmBundle.ts`): modern
 * lezer grammars first, legacy StreamLanguage grammars for everything else.
 * A generated test asserts every table value exists in `CM_MODE_KEYS`, so
 * the table can never drift from the bundle. Unknown extensions yield null
 * (plain-text editing) — a wrong grammar is worse than none, so mappings
 * stay conservative and conflicts resolve toward the most common use.
 */

/** Exported as a test surface: every value must exist in `CM_MODE_KEYS`. */
export const EXTENSION_TO_MODE_KEY: Record<string, string> = {
  // TypeScript / JavaScript
  ".ts": "typescript",
  ".tsx": "typescript",
  ".mts": "typescript",
  ".cts": "typescript",
  ".d.ts": "typescript",
  ".d.mts": "typescript",
  ".d.cts": "typescript",
  ".js": "javascript",
  ".jsx": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".es6": "javascript",
  ".es": "javascript",
  ".pac": "javascript",
  ".gs": "javascript",
  // JSON and JSON flavors
  ".json": "json",
  ".jsonc": "json",
  ".json5": "json",
  ".babelrc": "json",
  ".eslintrc": "json",
  ".prettierrc": "json",
  ".stylelintrc": "json",
  ".tsbuildinfo": "json",
  ".webmanifest": "json",
  ".geojson": "json",
  ".topojson": "json",
  ".ipynb": "json",
  ".har": "json",
  ".jsonl": "json",
  ".ndjson": "json",
  ".md": "markdown",
  ".txt": "markdown",
  ".text": "markdown",
  ".avsc": "json",
  ".gltf": "json",
  ".composer.lock": "json",
  ".pipfile.lock": "json",
  ".package.resolved": "json",
  ".flake.lock": "json",
  ".xctestplan": "json",
  ".xcstrings": "json",
  // Markdown and prose
  ".mdx": "markdown",
  ".markdown": "markdown",
  // Python
  ".py": "python",
  ".pyw": "python",
  ".pyi": "python",
  ".pyx": "cython",
  ".pxd": "cython",
  ".mojo": "python",
  ".gyp": "python",
  ".gypi": "python",
  ".bzl": "python",
  ".buck": "python",
  ".star": "python",
  ".meson.build": "python",
  // Ruby
  ".rb": "ruby",
  ".gemspec": "ruby",
  ".podspec": "ruby",
  ".rake": "ruby",
  ".ru": "ruby",
  // JVM / mobile
  ".java": "java",
  ".aidl": "java",
  ".pde": "java",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".gradle.kts": "kotlin",
  ".scala": "scala",
  ".sc": "scala",
  ".sbt": "scala",
  ".mill": "scala",
  ".groovy": "groovy",
  ".gvy": "groovy",
  ".gradle": "groovy",
  ".swift": "swift",
  ".m": "objectiveC",
  ".mm": "objectiveCpp",
  ".metal": "cpp",
  ".c": "c",
  ".h": "cpp",
  ".hpp": "cpp",
  ".hh": "cpp",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".cxx": "cpp",
  ".ino": "cpp",
  ".cu": "cpp",
  ".cuh": "cpp",
  ".cs": "csharp",
  ".cake": "csharp",
  ".csx": "csharp",
  ".fs": "fSharp",
  ".fsi": "fSharp",
  ".fsx": "fSharp",
  ".fsscript": "fSharp",
  ".vb": "vb",
  ".vba": "vb",
  ".bi": "vb",
  ".vbs": "vbScript",
  ".dart": "dart",
  ".hx": "haxe",
  ".hxml": "hxml",
  ".mxml": "xml",
  ".pas": "pascal",
  ".pp": "puppet",
  ".dpr": "pascal",
  ".lpr": "pascal",
  ".ppu": "pascal",
  ".f": "fortran",
  ".f90": "fortran",
  ".f95": "fortran",
  ".f03": "fortran",
  ".f08": "fortran",
  ".for": "fortran",
  ".ftn": "fortran",
  ".cob": "cobol",
  ".cbl": "cobol",
  ".cpy": "cobol",
  ".d": "d",
  ".di": "d",
  ".cr": "crystal",
  ".ecr": "crystal",
  ".go": "go",
  ".rs": "rust",
  ".swiftinterface": "swift",
  ".php": "php",
  ".php3": "php",
  ".php4": "php",
  ".php5": "php",
  ".phtml": "php",
  ".ctp": "php",
  ".blade.php": "php",
  ".sh": "shell",
  ".bash": "shell",
  ".zsh": "shell",
  ".fish": "shell",
  ".ksh": "shell",
  ".csh": "shell",
  ".tcsh": "shell",
  ".ebuild": "shell",
  ".eclass": "shell",
  ".profile": "shell",
  ".bashrc": "shell",
  ".bash_profile": "shell",
  ".zshrc": "shell",
  ".gradlew": "shell",
  ".mvnw": "shell",
  ".sql": "sql",
  ".pgsql": "pgSQL",
  ".mysql": "mySQL",
  ".maria": "mariaDB",
  ".sqlite": "sqlite",
  ".db": "sqlite",
  ".tsql": "msSQL",
  ".mssql": "msSQL",
  ".hql": "hive",
  ".hive": "hive",
  ".sparksql": "sparkSQL",
  ".plsql": "plSQL",
  ".pls": "plSQL",
  ".cql": "cassandra",
  ".solr": "solr",
  ".trig": "turtle",
  ".nq": "ntriples",
  ".nt": "ntriples",
  ".nquads": "ntriples",
  ".rq": "sparql",
  ".sparql": "sparql",
  ".cypher": "cypher",
  ".cyp": "cypher",
  // Web markup / styles
  ".html": "html",
  ".htm": "html",
  ".shtml": "html",
  ".rhtml": "html",
  ".erb": "html",
  ".svelte": "html",
  ".astro": "html",
  ".vue": "vue",
  ".css": "css",
  ".scss": "sCSS",
  ".sass": "sass",
  ".less": "less",
  ".styl": "stylus",
  ".stylus": "stylus",
  ".uss": "css",
  ".qss": "css",
  // Config / data
  ".xml": "xml",
  ".xhtml": "xml",
  ".rss": "xml",
  ".atom": "xml",
  ".xsd": "xml",
  ".xsl": "xml",
  ".plist": "xml",
  ".svg": "xml",
  ".csproj": "xml",
  ".vcxproj": "xml",
  ".resx": "xml",
  ".config": "xml",
  ".nuspec": "xml",
  ".wsdl": "xml",
  ".xaml": "xml",
  ".axml": "xml",
  ".opml": "xml",
  ".rdf": "xml",
  ".scxml": "xml",
  ".ssml": "xml",
  ".xht": "xml",
  ".tag": "xml",
  ".tld": "xml",
  ".jspx": "xml",
  ".xmi": "xml",
  ".rng": "xml",
  ".vxml": "xml",
  ".wixproj": "xml",
  ".wxs": "xml",
  ".xbl": "xml",
  ".xul": "xml",
  ".dita": "xml",
  ".ditamap": "xml",
  ".ditaval": "xml",
  ".fo": "xml",
  ".jmx": "xml",
  ".launch": "xml",
  ".mxml2": "xml",
  ".urdf": "xml",
  ".xacro": "xml",
  ".sdf": "xml",
  ".world": "xml",
  ".dae": "xml",
  ".qrc": "xml",
  ".ui": "xml",
  ".storyboard": "xml",
  ".xib": "xml",
  ".entitlements": "xml",
  ".stringsdict": "xml",
  ".intentdefinition": "xml",
  ".yml": "yaml",
  ".yaml": "yaml",
  ".eyaml": "yaml",
  ".raml": "yaml",
  ".sls": "yaml",
  ".unity": "yaml",
  ".meta": "yaml",
  ".prefab": "yaml",
  ".asset": "yaml",
  ".controller": "yaml",
  ".spriteatlas": "yaml",
  ".toml": "toml",
  ".ini": "properties",
  ".cfg": "properties",
  ".conf": "properties",
  ".cnf": "properties",
  ".properties": "properties",
  ".env": "properties",
  ".gitignore": "properties",
  ".gitattributes": "properties",
  ".gitconfig": "properties",
  ".gitmodules": "properties",
  ".editorconfig": "properties",
  ".npmrc": "properties",
  ".yarnrc": "properties",
  ".flake8": "properties",
  ".coveragerc": "properties",
  ".pypirc": "properties",
  ".buckconfig": "properties",
  ".xcconfig": "properties",
  ".strings": "properties",
  ".reg": "properties",
  // Docker / build
  ".dockerfile": "dockerFile",
  ".cmake": "cmake",
  ".ninja": "cmake",
  ".gni": "python",
  ".isolate": "python",
  // Scripting languages
  ".pl": "perl",
  ".pm": "perl",
  ".t": "perl",
  ".lua": "lua",
  ".r": "r",
  ".jl": "julia",
  ".hs": "haskell",
  ".lhs": "haskell",
  ".hs-boot": "haskell",
  ".purs": "haskell",
  ".ml": "oCaml",
  ".mli": "oCaml",
  ".mll": "oCaml",
  ".mly": "oCaml",
  ".sml": "sml",
  ".sig": "sml",
  ".elm": "elm",
  ".erl": "erlang",
  ".hrl": "erlang",
  ".clj": "clojure",
  ".cljs": "clojure",
  ".cljc": "clojure",
  ".edn": "clojure",
  ".bb": "clojure",
  ".lisp": "commonLisp",
  ".lsp": "commonLisp",
  ".el": "commonLisp",
  ".asd": "commonLisp",
  ".scm": "scheme",
  ".ss": "scheme",
  ".rkt": "scheme",
  ".scrbl": "scheme",
  ".rktl": "scheme",
  ".st": "smalltalk",
  ".fth": "forth",
  ".forth": "forth",
  ".tcl": "tcl",
  ".awk": "gas",
  ".sed": "gas",
  ".s": "gas",
  ".asm": "gas",
  ".inc": "gas",
  ".m4": "gas",
  ".v": "verilog",
  ".sv": "verilog",
  ".svh": "verilog",
  ".vhd": "vhdl",
  ".vhdl": "vhdl",
  ".ps1": "powerShell",
  ".psd1": "powerShell",
  ".psm1": "powerShell",
  ".ps1xml": "xml",
  ".bat": "vb",
  ".cmd": "vb",
  // Templates
  ".pug": "pug",
  ".jade": "pug",
  ".twig": "jinja",
  ".njk": "jinja",
  ".jinja": "jinja",
  ".jinja2": "jinja2",
  ".j2": "jinja2",
  ".liquid": "liquid",
  // Misc text-ish
  ".diff": "diff",
  ".patch": "diff",
  ".udiff": "diff",
  ".orig": "diff",
  ".rej": "diff",
  ".http": "http",
  ".graphql": "gql",
  ".gql": "gql",
  ".graphqls": "gql",
  ".proto": "protobuf",
  ".proto3": "protobuf",
  ".fbs": "protobuf",
  ".thrift": "protobuf",
  ".avro": "json",
  ".g4": "ebnf",
  ".ebnf": "ebnf",
  ".bnf": "ebnf",
  ".abnf": "ebnf",
  ".pegjs": "pegjs",
  ".peg": "pegjs",
  ".leg": "pegjs",
  ".asn": "asn1",
  ".asn1": "asn1",
  ".ttl": "turtle",
  ".n3": "turtle",
  ".mbox": "mbox",
  ".eml": "mbox",
  ".ics": "properties",
  ".vcf": "properties",
  ".map": "properties",
  ".lst": "properties",
  ".log": "properties",
  ".tmp": "properties",
  ".temp": "properties",
  ".bak": "properties",
  ".out": "properties",
  ".dat": "properties",
  ".p": "pascal",
  ".dts": "dtd",
  ".rng-compact": "xml",
  ".rnc": "xml",
  ".sch": "scheme",
  ".shx": "shell",
  ".uix": "xml",
  ".tsd": "xml",
  ".odd": "xml",
  ".pmd": "xml",
  ".pml": "xml",
  ".pt": "xml",
  ".pxml": "xml",
  ".res": "xml",
  ".skeleton": "xml",
  ".sld": "xml",
  ".zone": "xml",
  ".glb": "json",
  ".uxml": "xml",
  ".cginc": "shader",
  ".compute": "shader",
  ".hlsl": "shader",
  ".vert": "shader",
  ".frag": "shader",
  ".geom": "shader",
  ".tesc": "shader",
  ".tese": "shader",
  ".glsl": "shader",
  ".wgsl": "wast",
  ".wat": "wast",
  ".wast": "wast",
  ".spv": "wast",
  ".spvasm": "wast",
  ".tml": "toml",
  ".flaskenv": "properties",
  ".htaccess": "properties",
  ".htpasswd": "properties",
  ".mailmap": "properties",
  ".node-version": "properties",
  ".nvmrc": "properties",
  ".ruby-version": "properties",
  ".python-version": "properties",
  ".java-version": "properties",
  ".go-version": "properties",
  ".terraform-version": "properties",
  ".tool-versions": "properties",
  ".dockerignore": "dockerFile",
  ".gcloudignore": "properties",
  ".slugignore": "properties",
  ".npmignore": "properties",
  ".vercelignore": "properties",
  ".prettierignore": "properties",
  ".eslintignore": "properties",
  ".stylelintignore": "properties",
  ".vscodeignore": "properties",
  ".gitkeep": "properties",
  ".keep": "properties",
  ".DS_Store": "properties",
  ".mrconfig": "properties",
  ".hgrc": "properties",
  ".selected_editor": "properties",
  // Lockfiles with real grammars
  ".podfile.lock": "yaml",
  ".poetry.lock": "toml",
  ".pdm.lock": "toml",
  ".uv.lock": "toml",
  ".cargo.lock": "toml",
  ".chart.lock": "yaml",
  ".pixi.lock": "toml",
  ".bun.lock": "json",
  ".deno.lock": "json",
  // Build files
  ".bazel": "python",
  ".meson.options": "python",
  ".conanfile.txt": "properties",
  ".workspace.bazel": "python",
  ".user.ini": "properties",
  ".my.cnf": "properties",
  ".mlmodel": "xml",
  // Niche legacy-modes grammars (every value verified in CM_MODE_KEYS)
  ".bf": "brainfuck",
  ".apl": "apl",
  ".dyl": "dylan",
  ".dylan": "dylan",
  ".e": "eiffel",
  ".eiffel": "eiffel",
  ".factor": "factor",
  ".mrc": "mirc",
  ".mirc": "mirc",
  ".msc": "mscgen",
  ".mscgen": "mscgen",
  ".mo": "modelica",
  ".sas": "sas",
  ".tlv": "tlv",
  ".gss": "gss",
  ".idl": "idl",
  ".webidl": "webIDL",
  ".q": "q",
  ".sieve": "sieve",
  ".csv": "spreadsheet",
  ".tsv": "spreadsheet",
  ".dtd": "dtd",
  ".man": "troff",
  ".1": "troff",
  ".nsi": "nsis",
  ".nsh": "nsis",
  ".jsonld": "jsonld",
  ".mps": "mumps",
  ".oz": "oz",
  ".tex": "stex",
  ".sty": "stex",
  ".cls": "stex",
  ".ltx": "stex",
  ".textile": "textile",
  ".tiki": "tiki",
  ".vm": "velocity",
  ".vsl": "velocity",
  ".ys": "yacas",
};

const BARE_FILENAMES: Record<string, string> = {
  dockerfile: ".dockerfile",
  gemfile: ".rb",
  rakefile: ".rb",
  vagrantfile: ".rb",
  brewfile: ".rb",
  cmakelists: ".cmake",
  jenkinsfile: ".groovy",
  tiltfile: ".py",
  sconstruct: ".py",
  sconscript: ".py",
  wscript: ".py",
  buck: ".buck",
  targets: ".buck",
  workspace: ".buck",
  build: ".buck",
  fastfile: ".rb",
  appfile: ".rb",
  matchfile: ".rb",
  gymfile: ".rb",
  scanfile: ".rb",
  snapfile: ".rb",
  deliverfile: ".rb",
  pluginfile: ".rb",
  dangerfile: ".rb",
  thorfile: ".rb",
  cheffile: ".rb",
  berksfile: ".rb",
  guardfile: ".rb",
  capfile: ".rb",
  rantfile: ".rb",
  caskfile: ".rb",
  mintfile: ".rb",
  podfile: ".rb",
  cartfile: ".rb",
  dangerfilejs: ".js",
  buildfile: ".buck",
  skaffold: ".yaml",
  containerfile: ".dockerfile",
  cmakecache: ".cmake",
  conanfile: ".py",
  mesonbuild: ".meson.build",
  workspacebazel: ".workspace.bazel",
  taskfile: ".yaml",
  earthfile: ".dockerfile",
  procfile: ".yaml",
  appveyor: ".yaml",
  codeowners: ".properties",
  gitignore: ".gitignore",
  mailmap: ".mailmap",
  gitconfig: ".gitconfig",
  gitmodules: ".gitmodules",
  npmrc: ".npmrc",
  yarnrc: ".yarnrc",
  babelrc: ".babelrc",
  eslintrc: ".eslintrc",
  prettierrc: ".prettierrc",
  stylelintrc: ".stylelintrc",
  gemspec: ".rb",
  podspec: ".rb",
  brewfilejson: ".json",
  configureac: ".sh",
 cmakecachetxt: ".cmake",
  license: ".md",
  copying: ".md",
  readme: ".md",
  changelog: ".md",
  authors: ".md",
  news: ".md",
  todo: ".md",
  contributing: ".md",
  maintainers: ".md",
  codeofconduct: ".md",
  securitymd: ".md",
};

export function extensionOfFileName(name: string): string {
  const base = name.split("/").pop() ?? name;
  const lower = base.toLowerCase();
  if (lower.startsWith(".env")) {
    const rest = lower.slice(4);
    if (rest === "" || rest.startsWith(".")) return ".env";
  }
  // `Dockerfile.<target>` variants (e.g. Dockerfile.prod) share the base grammar.
  if (lower === "dockerfile" || lower.startsWith("dockerfile.")) {
    return ".dockerfile";
  }
  // `CMakeLists.txt` / `CMakeCache.txt` would otherwise resolve via `.txt`.
  if (lower === "cmakelists.txt" || lower === "cmakecache.txt") {
    return ".cmake";
  }
  const dot = base.lastIndexOf(".");
  if (dot <= 0) {
    // Dotfiles (`.gitignore`) strip the leading dot for the BARE lookup.
    return BARE_FILENAMES[lower] ?? BARE_FILENAMES[lower.replace(/^\./, "")] ?? "";
  }
  const fullExt = base.slice(dot).toLowerCase();
  if (fullExt in EXTENSION_TO_MODE_KEY) return fullExt;
  // Multi-part extensions resolve longest-first (e.g. `.blade.php`,
  // `Pipfile.lock`); the dotted form handles leading-dot-less names.
  const dotted = lower.startsWith(".") ? lower : `.${lower}`;
  const multi = Object.keys(EXTENSION_TO_MODE_KEY)
    .filter((key) => key.includes(".", 1) && dotted.endsWith(key))
    .sort((a, b) => b.length - a.length);
  if (multi[0]) return multi[0];
  return fullExt;
}

/** Grammar key for a path, or null for plain text. */
export function grammarKeyForPath(path: string): string | null {
  const extension = extensionOfFileName(path);
  if (!extension) return null;
  return EXTENSION_TO_MODE_KEY[extension] ?? null;
}
