/**
 * Plugin runtime bridge (prompt §19, §42, §45, §48-§50, §57, §72, §73).
 *
 * One object owns the whole DOM execution path so no React component has to
 * reassemble it:
 *
 *   RN surface  ──post──▶  plugin host document (real DOM, generated by
 *                          `dom-runtime-script.ts`)
 *        ▲                        │
 *        └────handleMessage───────┘
 *
 * Responsibilities:
 * - mount/attach semantics: the execution host is registered with the Acode
 *   runtime *only while a document is live*, so an unmounted document can
 *   never be mistaken for a plugin crash (activation falls back to the
 *   declarative path with a diagnostic instead of marking plugins broken).
 * - restart: when the document reloads, plugins that were live are re-defined
 *   and re-initialized (`ExtensionRuntime.restoreActivePlugins`), because the
 *   document's own state died with it.
 * - commands (§45): registrations from the document are mirrored into an
 *   app-level registry that can list and invoke them.
 * - diagnostics (§52/§57): plugin console output, refused bridge operations,
 *   and lifecycle failures land in the persisted diagnostics log.
 * - install consent (§42): `acode.installPlugin` never installs anything by
 *   itself; it awaits a handler that runs Ajiro's own consent + install flow.
 * - notifications (§63): `acode.pushNotification` is surfaced as an in-app
 *   notice and recorded in diagnostics.
 */
import { emitExtensionEvent } from "../events";
import type { FormatterSelectionStore } from "../formatters";
import {
  createPluginCommandRegistry,
  type PluginCommandRegistry,
} from "../command-registry";
import { createDiagnosticRecorder, type DiagnosticRecorder } from "../diagnostics";
import { loadInstalledRecords, type InstallDeps } from "../installer";
import { acodePlatformForOS, type KeyBindingResolution } from "../key-bindings";
import type { ExtensionDiagnostic } from "../models";
import type { ExtensionRuntime } from "../runtime";
import type {
  PluginDialogKind,
  PluginDialogPayload,
  PluginPageState,
} from "./bridge-protocol";
import { buildPluginHostDocument } from "./dom-runtime-script";
import { createPluginHostServices } from "./host-services";
import {
  PluginDomHost,
  type PluginHostTransport,
} from "./plugin-host";

export type PluginRuntimeStatus = {
  page: PluginPageState;
  /** True once the mounted document has installed its runtime. */
  ready: boolean;
};

export type PluginNotification = {
  level: string;
  pluginId: string;
  text: string;
};

/**
 * Consent hook for `acode.installPlugin(pluginId)`. It must resolve only
 * after Ajiro's own install flow has finished, so the requesting plugin sees
 * the real outcome (§42).
 */
export type PluginInstallRequestHandler = (
  pluginId: string,
  targetId: string,
) => Promise<void>;

/**
 * App-side renderer for plugin dialogs, loaders, toasts, the file browser,
 * and new editor files (verified against Acode's `src/dialogs/*`). The
 * bridge ships honest defaults that refuse loudly, so a missing surface
 * reads as "not wired" rather than a silent swallow — except `toast` and
 * the loader ops, which degrade to diagnostics/no-ops like Acode's own
 * fire-and-forget paths.
 */
export type PluginUiHandler = {
  showDialog(kind: PluginDialogKind, payload: PluginDialogPayload): Promise<unknown>;
  createLoader(pluginId: string, title: string, message: string, timeoutMs?: number): Promise<string>;
  operateLoader(loaderId: string, op: "hide" | "setMessage" | "setTitle" | "show", value?: string): void;
  destroyLoader(loaderId: string): void;
  toast(pluginId: string, text: string, durationMs?: number): void;
  pickFiles(pluginId: string, mode: string): Promise<string[]>;
  openNewFile(pluginId: string, filename: string, text: string): Promise<string>;
};

export type PluginRuntimeBridge = {
  /** Attach a freshly mounted document, then restart live plugins. */
  attachDocument(transport: PluginHostTransport): Promise<void>;
  buildDocument(theme: {
    accent: string;
    background: string;
    backgroundElement: string;
    border: string;
    text: string;
    textSecondary: string;
  }): string;
  /** Canonical chord ids currently owned by plugin commands (§45). */
  chordIds(): string[];
  clearDiagnostics(pluginId?: string): Promise<void>;
  commands: PluginCommandRegistry;
  /** Tear the document down: no plugin code can run until it is re-attached. */
  detachDocument(): void;
  /**
   * True when at least one installed extension ships an entry script, i.e.
   * when mounting the plugin document can accomplish anything at all.
   */
  /** Feed one raw message from the mounted document. */
  handleMessage(raw: string): void;
  /**
   * Dispatch one editor chord to the plugin command that owns it. Reports
   * `conflict`/`unbound` instead of guessing, so a contested or stale binding
   * never runs the wrong plugin's code.
   */
  handleCommandKey(chordId: string): KeyBindingResolution;
  hasExecutableExtensions(): Promise<boolean>;
  hidePage(): void;
  host: PluginDomHost;
  listDiagnostics(pluginId?: string): Promise<ExtensionDiagnostic[]>;
  runCommand(name: string, value?: unknown): boolean;
  setInstallRequestHandler(handler: PluginInstallRequestHandler | null): void;
  setNotifyHandler(handler: ((notice: PluginNotification) => void) | null): void;
  setUiHandler(handler: PluginUiHandler | null): void;
  status(): PluginRuntimeStatus;
  subscribe(listener: (status: PluginRuntimeStatus) => void): () => void;
};

export function createPluginRuntimeBridge(input: {
  deps: InstallDeps;
  diagnostics?: DiagnosticRecorder;
  /** Per-language formatter selections (persisted by the caller). */
  formatterSelections?: FormatterSelectionStore;
  /** OS whose `bindKey` entry applies; defaults to the “win” map (§45). */
  os?: string;
  runtime: ExtensionRuntime;
}): PluginRuntimeBridge {
  const { deps, runtime } = input;
  const diagnostics = input.diagnostics ?? createDiagnosticRecorder(deps);
  // Commands execute inside the document, where the plugin's own closures
  // live; the host is bound below, once it exists.
  let invokeCommand: ((name: string) => void) | null = null;
  const commands = createPluginCommandRegistry(
    (name) => {
      invokeCommand?.(name);
    },
    { platform: acodePlatformForOS(input.os ?? "android") },
  );

  const listeners = new Set<(status: PluginRuntimeStatus) => void>();
  let installHandler: PluginInstallRequestHandler | null = null;
  let notifyHandler: ((notice: PluginNotification) => void) | null = null;
  let uiHandler: PluginUiHandler | null = null;
  let ready = false;

  const services = createPluginHostServices({
    callbacks: {
      async showDialog(kind, payload) {
        if (!uiHandler) {
          throw new Error(
            "Plugin dialogs are not available: the app surface has not wired a dialog handler.",
          );
        }
        return uiHandler.showDialog(kind, payload);
      },
      async createLoader(pluginId, title, message, timeoutMs) {
        if (!uiHandler) {
          throw new Error(
            "Plugin loaders are not available: the app surface has not wired a dialog handler.",
          );
        }
        return uiHandler.createLoader(pluginId, title, message, timeoutMs);
      },
      operateLoader(loaderId, op, value) {
        uiHandler?.operateLoader(loaderId, op, value);
      },
      destroyLoader(loaderId) {
        uiHandler?.destroyLoader(loaderId);
      },
      toast(pluginId, text, durationMs) {
        uiHandler?.toast(pluginId, text, durationMs);
      },
      async pickFiles(pluginId, mode) {
        if (!uiHandler) {
          throw new Error(
            "The file browser is not available: the app surface has not wired a dialog handler.",
          );
        }
        return uiHandler.pickFiles(pluginId, mode);
      },
      async openNewFile(pluginId, filename, text) {
        if (!uiHandler) {
          throw new Error(
            "Creating editor files is not available: the app surface has not wired a dialog handler.",
          );
        }
        return uiHandler.openNewFile(pluginId, filename, text);
      },
      log(pluginId, level, message) {
        // Persistence happens in the host services; this only fans the line
        // out to interested surfaces (the Store's diagnostics panel).
        emitExtensionEvent({ level, message, pluginId, type: "plugin-log" });
      },
      notify(pluginId, level, text) {
        const notice: PluginNotification = { level, pluginId, text };
        emitExtensionEvent({
          level,
          pluginId,
          text,
          type: "notification",
        });
        notifyHandler?.(notice);
      },
      onCommandRegistered(pluginId, command) {
        commands.register(pluginId, command);
      },
      onCommandRemoved(pluginId, name) {
        commands.remove(pluginId, name);
      },
      async requestPluginInstall(pluginId, targetId) {
        if (!installHandler) {
          throw new Error(
            "Plugin installation requests are disabled: an extension cannot install other extensions without user consent.",
          );
        }
        await installHandler(pluginId, targetId);
      },
    },
    deps,
    diagnostics,
  });

  const host = new PluginDomHost(services, undefined, input.formatterSelections);
  invokeCommand = (name) => {
    host.runCommand(name);
  };

  // Commands are executed inside the document, where the plugin's own
  // closures live; the registry only mirrors them (§45).
  commands.subscribe(() => {
    emitExtensionEvent({ type: "commands-changed" });
  });

  const status = (): PluginRuntimeStatus => ({
    page: host.getPage(),
    ready: ready && host.isReady(),
  });

  function emitStatus(): void {
    const snapshot = status();
    for (const listener of [...listeners]) {
      try {
        listener(snapshot);
      } catch {
        // A broken listener must not break the runtime.
      }
    }
  }

  host.subscribe((event) => {
    switch (event.type) {
      case "activated":
        emitStatus();
        return;
      case "unmounted":
        // An unmounted plugin's commands died with its document state, so the
        // mirrored registry must not keep offering them (§45).
        commands.clear(event.pluginId);
        emitStatus();
        return;
      case "commands-changed":
        return;
      case "page":
        emitStatus();
        return;
      case "error":
        // The runtime turns activate/load failures into broken marks; the
        // host reports every failure so diagnostics stay complete.
        void diagnostics
          .record(event.pluginId, "error", `${event.phase}: ${event.message}`)
          .catch(() => {});
        return;
      default:
        return;
    }
  });

  return {
    chordIds: () => commands.chordIds(),

    commands,

    async attachDocument(transport) {
      host.attach(transport);
      // The runtime may only execute plugin code through a live document.
      runtime.setExecutionHost(host);
      runtime.setPluginStoreReader(services);
      await host.waitForReady();
      ready = true;
      emitStatus();
      await runtime.restoreActivePlugins();
    },

    buildDocument(theme) {
      return buildPluginHostDocument({ theme });
    },

    async clearDiagnostics(pluginId) {
      await diagnostics.clear(pluginId);
      emitExtensionEvent({ pluginId: pluginId ?? null, type: "diagnostics-changed" });
    },

    detachDocument() {
      ready = false;
      host.detach();
      runtime.setExecutionHost(null);
      runtime.setPluginStoreReader(null);
      commands.clear();
      emitStatus();
    },

    handleCommandKey(chordId) {
      return commands.invokeChord(chordId);
    },

    handleMessage(raw) {
      host.handleMessage(raw);
    },

    async hasExecutableExtensions() {
      const records = await loadInstalledRecords(deps).catch(() => []);
      return records.some(
        (record) => typeof record.manifest.main === "string" && record.manifest.main !== "",
      );
    },

    hidePage() {
      host.hidePage();
      emitStatus();
    },

    host,

    listDiagnostics(pluginId) {
      return diagnostics.list(pluginId);
    },

    runCommand(name, value) {
      return host.runCommand(name, value);
    },

    setInstallRequestHandler(handler) {
      installHandler = handler;
    },

    setNotifyHandler(handler) {
      notifyHandler = handler;
    },

    setUiHandler(handler) {
      uiHandler = handler;
    },

    status,

    subscribe(listener) {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    },
  };
}
