// GENERATED by scripts/vendor-cm.mjs — do not edit by hand.
import { EditorState, Compartment, Prec } from "@codemirror/state";
import {
  EditorView, keymap, lineNumbers, highlightActiveLineGutter,
  highlightSpecialChars, drawSelection, dropCursor, rectangularSelection,
  crosshairCursor, highlightActiveLine,
} from "@codemirror/view";
import {
  defaultKeymap, history, historyKeymap, indentMore, indentLess,
  undo, redo,
} from "@codemirror/commands";
import {
  foldGutter, foldAll, unfoldAll, foldEffect, foldKeymap,
  syntaxHighlighting, HighlightStyle, StreamLanguage, LanguageSupport,
  defaultHighlightStyle, indentOnInput,
} from "@codemirror/language";
import {
  autocompletion, closeBrackets, closeBracketsKeymap, acceptCompletion,
  completionKeymap, closeCompletion, completeAnyWord, startCompletion,
} from "@codemirror/autocomplete";
import {
  SearchQuery, findNext, findPrevious, selectNextOccurrence,
  selectSelectionMatches, replaceNext, replaceAll, setSearchQuery,
  getSearchQuery, search, SearchCursor,
} from "@codemirror/search";
import {
  abbreviationTracker, emmetCompletionSource, expandAbbreviation,
} from "@emmetio/codemirror6-plugin";
import { tags } from "@lezer/highlight";
import { javascript as modern_javascript } from "@codemirror/lang-javascript";
import { python as modern_python } from "@codemirror/lang-python";
import { java as modern_java } from "@codemirror/lang-java";
import { cpp as modern_cpp } from "@codemirror/lang-cpp";
import { go as modern_go } from "@codemirror/lang-go";
import { rust as modern_rust } from "@codemirror/lang-rust";
import { php as modern_php } from "@codemirror/lang-php";
import { sql as modern_sql } from "@codemirror/lang-sql";
import { html as modern_html } from "@codemirror/lang-html";
import { css as modern_css } from "@codemirror/lang-css";
import { json as modern_json } from "@codemirror/lang-json";
import { markdown as modern_markdown } from "@codemirror/lang-markdown";
import { xml as modern_xml } from "@codemirror/lang-xml";
import { yaml as modern_yaml } from "@codemirror/lang-yaml";
import { vue as modern_vue } from "@codemirror/lang-vue";
import { angular as modern_angular } from "@codemirror/lang-angular";
import { sass as modern_sass } from "@codemirror/lang-sass";
import { less as modern_less } from "@codemirror/lang-less";
import { jinja as modern_jinja } from "@codemirror/lang-jinja";
import { liquid as modern_liquid } from "@codemirror/lang-liquid";
import { wast as modern_wast } from "@codemirror/lang-wast";
import { apl as legacy0 } from "@codemirror/legacy-modes/mode/apl";
import { asciiArmor as legacy1 } from "@codemirror/legacy-modes/mode/asciiarmor";
import { asn1 as legacy2 } from "@codemirror/legacy-modes/mode/asn1";
import { asterisk as legacy3 } from "@codemirror/legacy-modes/mode/asterisk";
import { brainfuck as legacy4 } from "@codemirror/legacy-modes/mode/brainfuck";
import { c as legacy5 } from "@codemirror/legacy-modes/mode/clike";
import { ceylon as legacy6 } from "@codemirror/legacy-modes/mode/clike";
import { clike as legacy7 } from "@codemirror/legacy-modes/mode/clike";
import { cpp as legacy8 } from "@codemirror/legacy-modes/mode/clike";
import { csharp as legacy9 } from "@codemirror/legacy-modes/mode/clike";
import { dart as legacy10 } from "@codemirror/legacy-modes/mode/clike";
import { java as legacy11 } from "@codemirror/legacy-modes/mode/clike";
import { kotlin as legacy12 } from "@codemirror/legacy-modes/mode/clike";
import { nesC as legacy13 } from "@codemirror/legacy-modes/mode/clike";
import { objectiveC as legacy14 } from "@codemirror/legacy-modes/mode/clike";
import { objectiveCpp as legacy15 } from "@codemirror/legacy-modes/mode/clike";
import { scala as legacy16 } from "@codemirror/legacy-modes/mode/clike";
import { shader as legacy17 } from "@codemirror/legacy-modes/mode/clike";
import { squirrel as legacy18 } from "@codemirror/legacy-modes/mode/clike";
import { clojure as legacy19 } from "@codemirror/legacy-modes/mode/clojure";
import { cmake as legacy20 } from "@codemirror/legacy-modes/mode/cmake";
import { cobol as legacy21 } from "@codemirror/legacy-modes/mode/cobol";
import { coffeeScript as legacy22 } from "@codemirror/legacy-modes/mode/coffeescript";
import { commonLisp as legacy23 } from "@codemirror/legacy-modes/mode/commonlisp";
import { crystal as legacy24 } from "@codemirror/legacy-modes/mode/crystal";
import { css as legacy25 } from "@codemirror/legacy-modes/mode/css";
import { gss as legacy26 } from "@codemirror/legacy-modes/mode/css";
import { less as legacy27 } from "@codemirror/legacy-modes/mode/css";
import { mkCSS as legacy28 } from "@codemirror/legacy-modes/mode/css";
import { sCSS as legacy29 } from "@codemirror/legacy-modes/mode/css";
import { cypher as legacy30 } from "@codemirror/legacy-modes/mode/cypher";
import { d as legacy31 } from "@codemirror/legacy-modes/mode/d";
import { diff as legacy32 } from "@codemirror/legacy-modes/mode/diff";
import { dockerFile as legacy33 } from "@codemirror/legacy-modes/mode/dockerfile";
import { dtd as legacy34 } from "@codemirror/legacy-modes/mode/dtd";
import { dylan as legacy35 } from "@codemirror/legacy-modes/mode/dylan";
import { ebnf as legacy36 } from "@codemirror/legacy-modes/mode/ebnf";
import { ecl as legacy37 } from "@codemirror/legacy-modes/mode/ecl";
import { eiffel as legacy38 } from "@codemirror/legacy-modes/mode/eiffel";
import { elm as legacy39 } from "@codemirror/legacy-modes/mode/elm";
import { erlang as legacy40 } from "@codemirror/legacy-modes/mode/erlang";
import { factor as legacy41 } from "@codemirror/legacy-modes/mode/factor";
import { fcl as legacy42 } from "@codemirror/legacy-modes/mode/fcl";
import { forth as legacy43 } from "@codemirror/legacy-modes/mode/forth";
import { fortran as legacy44 } from "@codemirror/legacy-modes/mode/fortran";
import { gas as legacy45 } from "@codemirror/legacy-modes/mode/gas";
import { gasArm as legacy46 } from "@codemirror/legacy-modes/mode/gas";
import { gherkin as legacy47 } from "@codemirror/legacy-modes/mode/gherkin";
import { go as legacy48 } from "@codemirror/legacy-modes/mode/go";
import { groovy as legacy49 } from "@codemirror/legacy-modes/mode/groovy";
import { haskell as legacy50 } from "@codemirror/legacy-modes/mode/haskell";
import { haxe as legacy51 } from "@codemirror/legacy-modes/mode/haxe";
import { hxml as legacy52 } from "@codemirror/legacy-modes/mode/haxe";
import { http as legacy53 } from "@codemirror/legacy-modes/mode/http";
import { idl as legacy54 } from "@codemirror/legacy-modes/mode/idl";
import { javascript as legacy55 } from "@codemirror/legacy-modes/mode/javascript";
import { json as legacy56 } from "@codemirror/legacy-modes/mode/javascript";
import { jsonld as legacy57 } from "@codemirror/legacy-modes/mode/javascript";
import { typescript as legacy58 } from "@codemirror/legacy-modes/mode/javascript";
import { jinja2 as legacy59 } from "@codemirror/legacy-modes/mode/jinja2";
import { julia as legacy60 } from "@codemirror/legacy-modes/mode/julia";
import { liveScript as legacy61 } from "@codemirror/legacy-modes/mode/livescript";
import { lua as legacy62 } from "@codemirror/legacy-modes/mode/lua";
import { mathematica as legacy63 } from "@codemirror/legacy-modes/mode/mathematica";
import { mbox as legacy64 } from "@codemirror/legacy-modes/mode/mbox";
import { mirc as legacy65 } from "@codemirror/legacy-modes/mode/mirc";
import { fSharp as legacy66 } from "@codemirror/legacy-modes/mode/mllike";
import { oCaml as legacy67 } from "@codemirror/legacy-modes/mode/mllike";
import { sml as legacy68 } from "@codemirror/legacy-modes/mode/mllike";
import { modelica as legacy69 } from "@codemirror/legacy-modes/mode/modelica";
import { mscgen as legacy70 } from "@codemirror/legacy-modes/mode/mscgen";
import { msgenny as legacy71 } from "@codemirror/legacy-modes/mode/mscgen";
import { xu as legacy72 } from "@codemirror/legacy-modes/mode/mscgen";
import { mumps as legacy73 } from "@codemirror/legacy-modes/mode/mumps";
import { nginx as legacy74 } from "@codemirror/legacy-modes/mode/nginx";
import { nsis as legacy75 } from "@codemirror/legacy-modes/mode/nsis";
import { ntriples as legacy76 } from "@codemirror/legacy-modes/mode/ntriples";
import { octave as legacy77 } from "@codemirror/legacy-modes/mode/octave";
import { oz as legacy78 } from "@codemirror/legacy-modes/mode/oz";
import { pascal as legacy79 } from "@codemirror/legacy-modes/mode/pascal";
import { pegjs as legacy80 } from "@codemirror/legacy-modes/mode/pegjs";
import { perl as legacy81 } from "@codemirror/legacy-modes/mode/perl";
import { pig as legacy82 } from "@codemirror/legacy-modes/mode/pig";
import { powerShell as legacy83 } from "@codemirror/legacy-modes/mode/powershell";
import { properties as legacy84 } from "@codemirror/legacy-modes/mode/properties";
import { protobuf as legacy85 } from "@codemirror/legacy-modes/mode/protobuf";
import { pug as legacy86 } from "@codemirror/legacy-modes/mode/pug";
import { puppet as legacy87 } from "@codemirror/legacy-modes/mode/puppet";
import { cython as legacy88 } from "@codemirror/legacy-modes/mode/python";
import { mkPython as legacy89 } from "@codemirror/legacy-modes/mode/python";
import { python as legacy90 } from "@codemirror/legacy-modes/mode/python";
import { q as legacy91 } from "@codemirror/legacy-modes/mode/q";
import { r as legacy92 } from "@codemirror/legacy-modes/mode/r";
import { rpmChanges as legacy93 } from "@codemirror/legacy-modes/mode/rpm";
import { rpmSpec as legacy94 } from "@codemirror/legacy-modes/mode/rpm";
import { ruby as legacy95 } from "@codemirror/legacy-modes/mode/ruby";
import { rust as legacy96 } from "@codemirror/legacy-modes/mode/rust";
import { sas as legacy97 } from "@codemirror/legacy-modes/mode/sas";
import { sass as legacy98 } from "@codemirror/legacy-modes/mode/sass";
import { scheme as legacy99 } from "@codemirror/legacy-modes/mode/scheme";
import { shell as legacy100 } from "@codemirror/legacy-modes/mode/shell";
import { sieve as legacy101 } from "@codemirror/legacy-modes/mode/sieve";
import { smalltalk as legacy102 } from "@codemirror/legacy-modes/mode/smalltalk";
import { solr as legacy103 } from "@codemirror/legacy-modes/mode/solr";
import { sparql as legacy104 } from "@codemirror/legacy-modes/mode/sparql";
import { spreadsheet as legacy105 } from "@codemirror/legacy-modes/mode/spreadsheet";
import { cassandra as legacy106 } from "@codemirror/legacy-modes/mode/sql";
import { esper as legacy107 } from "@codemirror/legacy-modes/mode/sql";
import { gpSQL as legacy108 } from "@codemirror/legacy-modes/mode/sql";
import { gql as legacy109 } from "@codemirror/legacy-modes/mode/sql";
import { hive as legacy110 } from "@codemirror/legacy-modes/mode/sql";
import { mariaDB as legacy111 } from "@codemirror/legacy-modes/mode/sql";
import { msSQL as legacy112 } from "@codemirror/legacy-modes/mode/sql";
import { mySQL as legacy113 } from "@codemirror/legacy-modes/mode/sql";
import { pgSQL as legacy114 } from "@codemirror/legacy-modes/mode/sql";
import { plSQL as legacy115 } from "@codemirror/legacy-modes/mode/sql";
import { sparkSQL as legacy116 } from "@codemirror/legacy-modes/mode/sql";
import { sql as legacy117 } from "@codemirror/legacy-modes/mode/sql";
import { sqlite as legacy118 } from "@codemirror/legacy-modes/mode/sql";
import { standardSQL as legacy119 } from "@codemirror/legacy-modes/mode/sql";
import { stex as legacy120 } from "@codemirror/legacy-modes/mode/stex";
import { stexMath as legacy121 } from "@codemirror/legacy-modes/mode/stex";
import { stylus as legacy122 } from "@codemirror/legacy-modes/mode/stylus";
import { swift as legacy123 } from "@codemirror/legacy-modes/mode/swift";
import { tcl as legacy124 } from "@codemirror/legacy-modes/mode/tcl";
import { textile as legacy125 } from "@codemirror/legacy-modes/mode/textile";
import { tiddlyWiki as legacy126 } from "@codemirror/legacy-modes/mode/tiddlywiki";
import { tiki as legacy127 } from "@codemirror/legacy-modes/mode/tiki";
import { toml as legacy128 } from "@codemirror/legacy-modes/mode/toml";
import { troff as legacy129 } from "@codemirror/legacy-modes/mode/troff";
import { ttcnCfg as legacy130 } from "@codemirror/legacy-modes/mode/ttcn-cfg";
import { ttcn as legacy131 } from "@codemirror/legacy-modes/mode/ttcn";
import { turtle as legacy132 } from "@codemirror/legacy-modes/mode/turtle";
import { vb as legacy133 } from "@codemirror/legacy-modes/mode/vb";
import { vbScript as legacy134 } from "@codemirror/legacy-modes/mode/vbscript";
import { vbScriptASP as legacy135 } from "@codemirror/legacy-modes/mode/vbscript";
import { velocity as legacy136 } from "@codemirror/legacy-modes/mode/velocity";
import { tlv as legacy137 } from "@codemirror/legacy-modes/mode/verilog";
import { verilog as legacy138 } from "@codemirror/legacy-modes/mode/verilog";
import { vhdl as legacy139 } from "@codemirror/legacy-modes/mode/vhdl";
import { wast as legacy140 } from "@codemirror/legacy-modes/mode/wast";
import { webIDL as legacy141 } from "@codemirror/legacy-modes/mode/webidl";
import { html as legacy142 } from "@codemirror/legacy-modes/mode/xml";
import { mkXML as legacy143 } from "@codemirror/legacy-modes/mode/xml";
import { xml as legacy144 } from "@codemirror/legacy-modes/mode/xml";
import { xQuery as legacy145 } from "@codemirror/legacy-modes/mode/xquery";
import { yacas as legacy146 } from "@codemirror/legacy-modes/mode/yacas";
import { yaml as legacy147 } from "@codemirror/legacy-modes/mode/yaml";
import { ez80 as legacy148 } from "@codemirror/legacy-modes/mode/z80";
import { z80 as legacy149 } from "@codemirror/legacy-modes/mode/z80";

const MODERN_FACTORIES = {
  "javascript": modern_javascript,
  "python": modern_python,
  "java": modern_java,
  "cpp": modern_cpp,
  "go": modern_go,
  "rust": modern_rust,
  "php": modern_php,
  "sql": modern_sql,
  "html": modern_html,
  "css": modern_css,
  "json": modern_json,
  "markdown": modern_markdown,
  "xml": modern_xml,
  "yaml": modern_yaml,
  "vue": modern_vue,
  "angular": modern_angular,
  "sass": modern_sass,
  "less": modern_less,
  "jinja": modern_jinja,
  "liquid": modern_liquid,
  "wast": modern_wast,
};

const LEGACY_SUPPORTS = {
  "apl": StreamLanguage.define(legacy0),
  "asciiArmor": StreamLanguage.define(legacy1),
  "asn1": StreamLanguage.define(legacy2({})),
  "asterisk": StreamLanguage.define(legacy3),
  "brainfuck": StreamLanguage.define(legacy4),
  "c": StreamLanguage.define(legacy5),
  "ceylon": StreamLanguage.define(legacy6),
  "clike": StreamLanguage.define(legacy7({})),
  "cpp": StreamLanguage.define(legacy8),
  "csharp": StreamLanguage.define(legacy9),
  "dart": StreamLanguage.define(legacy10),
  "java": StreamLanguage.define(legacy11),
  "kotlin": StreamLanguage.define(legacy12),
  "nesC": StreamLanguage.define(legacy13),
  "objectiveC": StreamLanguage.define(legacy14),
  "objectiveCpp": StreamLanguage.define(legacy15),
  "scala": StreamLanguage.define(legacy16),
  "shader": StreamLanguage.define(legacy17),
  "squirrel": StreamLanguage.define(legacy18),
  "clojure": StreamLanguage.define(legacy19),
  "cmake": StreamLanguage.define(legacy20),
  "cobol": StreamLanguage.define(legacy21),
  "coffeeScript": StreamLanguage.define(legacy22),
  "commonLisp": StreamLanguage.define(legacy23),
  "crystal": StreamLanguage.define(legacy24),
  "css": StreamLanguage.define(legacy25),
  "gss": StreamLanguage.define(legacy26),
  "less": StreamLanguage.define(legacy27),
  "mkCSS": StreamLanguage.define(legacy28({})),
  "sCSS": StreamLanguage.define(legacy29),
  "cypher": StreamLanguage.define(legacy30),
  "d": StreamLanguage.define(legacy31),
  "diff": StreamLanguage.define(legacy32),
  "dockerFile": StreamLanguage.define(legacy33),
  "dtd": StreamLanguage.define(legacy34),
  "dylan": StreamLanguage.define(legacy35),
  "ebnf": StreamLanguage.define(legacy36),
  "ecl": StreamLanguage.define(legacy37),
  "eiffel": StreamLanguage.define(legacy38),
  "elm": StreamLanguage.define(legacy39),
  "erlang": StreamLanguage.define(legacy40),
  "factor": StreamLanguage.define(legacy41),
  "fcl": StreamLanguage.define(legacy42),
  "forth": StreamLanguage.define(legacy43),
  "fortran": StreamLanguage.define(legacy44),
  "gas": StreamLanguage.define(legacy45),
  "gasArm": StreamLanguage.define(legacy46),
  "gherkin": StreamLanguage.define(legacy47),
  "go": StreamLanguage.define(legacy48),
  "groovy": StreamLanguage.define(legacy49),
  "haskell": StreamLanguage.define(legacy50),
  "haxe": StreamLanguage.define(legacy51),
  "hxml": StreamLanguage.define(legacy52),
  "http": StreamLanguage.define(legacy53),
  "idl": StreamLanguage.define(legacy54),
  "javascript": StreamLanguage.define(legacy55),
  "json": StreamLanguage.define(legacy56),
  "jsonld": StreamLanguage.define(legacy57),
  "typescript": StreamLanguage.define(legacy58),
  "jinja2": StreamLanguage.define(legacy59),
  "julia": StreamLanguage.define(legacy60),
  "liveScript": StreamLanguage.define(legacy61),
  "lua": StreamLanguage.define(legacy62),
  "mathematica": StreamLanguage.define(legacy63),
  "mbox": StreamLanguage.define(legacy64),
  "mirc": StreamLanguage.define(legacy65),
  "fSharp": StreamLanguage.define(legacy66),
  "oCaml": StreamLanguage.define(legacy67),
  "sml": StreamLanguage.define(legacy68),
  "modelica": StreamLanguage.define(legacy69),
  "mscgen": StreamLanguage.define(legacy70),
  "msgenny": StreamLanguage.define(legacy71),
  "xu": StreamLanguage.define(legacy72),
  "mumps": StreamLanguage.define(legacy73),
  "nginx": StreamLanguage.define(legacy74),
  "nsis": StreamLanguage.define(legacy75),
  "ntriples": StreamLanguage.define(legacy76),
  "octave": StreamLanguage.define(legacy77),
  "oz": StreamLanguage.define(legacy78),
  "pascal": StreamLanguage.define(legacy79),
  "pegjs": StreamLanguage.define(legacy80),
  "perl": StreamLanguage.define(legacy81),
  "pig": StreamLanguage.define(legacy82),
  "powerShell": StreamLanguage.define(legacy83),
  "properties": StreamLanguage.define(legacy84),
  "protobuf": StreamLanguage.define(legacy85),
  "pug": StreamLanguage.define(legacy86),
  "puppet": StreamLanguage.define(legacy87),
  "cython": StreamLanguage.define(legacy88),
  "mkPython": StreamLanguage.define(legacy89({})),
  "python": StreamLanguage.define(legacy90),
  "q": StreamLanguage.define(legacy91),
  "r": StreamLanguage.define(legacy92),
  "rpmChanges": StreamLanguage.define(legacy93),
  "rpmSpec": StreamLanguage.define(legacy94),
  "ruby": StreamLanguage.define(legacy95),
  "rust": StreamLanguage.define(legacy96),
  "sas": StreamLanguage.define(legacy97),
  "sass": StreamLanguage.define(legacy98),
  "scheme": StreamLanguage.define(legacy99),
  "shell": StreamLanguage.define(legacy100),
  "sieve": StreamLanguage.define(legacy101),
  "smalltalk": StreamLanguage.define(legacy102),
  "solr": StreamLanguage.define(legacy103),
  "sparql": StreamLanguage.define(legacy104),
  "spreadsheet": StreamLanguage.define(legacy105),
  "cassandra": StreamLanguage.define(legacy106),
  "esper": StreamLanguage.define(legacy107),
  "gpSQL": StreamLanguage.define(legacy108),
  "gql": StreamLanguage.define(legacy109),
  "hive": StreamLanguage.define(legacy110),
  "mariaDB": StreamLanguage.define(legacy111),
  "msSQL": StreamLanguage.define(legacy112),
  "mySQL": StreamLanguage.define(legacy113),
  "pgSQL": StreamLanguage.define(legacy114),
  "plSQL": StreamLanguage.define(legacy115),
  "sparkSQL": StreamLanguage.define(legacy116),
  "sql": StreamLanguage.define(legacy117({})),
  "sqlite": StreamLanguage.define(legacy118),
  "standardSQL": StreamLanguage.define(legacy119),
  "stex": StreamLanguage.define(legacy120),
  "stexMath": StreamLanguage.define(legacy121),
  "stylus": StreamLanguage.define(legacy122),
  "swift": StreamLanguage.define(legacy123),
  "tcl": StreamLanguage.define(legacy124),
  "textile": StreamLanguage.define(legacy125),
  "tiddlyWiki": StreamLanguage.define(legacy126),
  "tiki": StreamLanguage.define(legacy127),
  "toml": StreamLanguage.define(legacy128),
  "troff": StreamLanguage.define(legacy129),
  "ttcnCfg": StreamLanguage.define(legacy130),
  "ttcn": StreamLanguage.define(legacy131),
  "turtle": StreamLanguage.define(legacy132),
  "vb": StreamLanguage.define(legacy133),
  "vbScript": StreamLanguage.define(legacy134),
  "vbScriptASP": StreamLanguage.define(legacy135),
  "velocity": StreamLanguage.define(legacy136),
  "tlv": StreamLanguage.define(legacy137),
  "verilog": StreamLanguage.define(legacy138),
  "vhdl": StreamLanguage.define(legacy139),
  "wast": StreamLanguage.define(legacy140),
  "webIDL": StreamLanguage.define(legacy141),
  "html": StreamLanguage.define(legacy142),
  "mkXML": StreamLanguage.define(legacy143({})),
  "xml": StreamLanguage.define(legacy144),
  "xQuery": StreamLanguage.define(legacy145),
  "yacas": StreamLanguage.define(legacy146),
  "yaml": StreamLanguage.define(legacy147),
  "ez80": StreamLanguage.define(legacy148),
  "z80": StreamLanguage.define(legacy149),
};

export const AjiroCM = {
  EditorState, EditorView, Compartment, Prec,
  keymap, lineNumbers, highlightActiveLineGutter, highlightSpecialChars,
  drawSelection, dropCursor, rectangularSelection, crosshairCursor,
  highlightActiveLine, defaultKeymap, history, historyKeymap, indentOnInput,
  indentMore, indentLess, undo, redo, foldGutter, foldAll, unfoldAll, foldEffect, foldKeymap,
  syntaxHighlighting, HighlightStyle, defaultHighlightStyle,
  autocompletion, closeBrackets, closeBracketsKeymap, acceptCompletion,
  completionKeymap, closeCompletion, completeAnyWord, startCompletion,
  SearchQuery, findNext, findPrevious, selectNextOccurrence,
  selectSelectionMatches, replaceNext, replaceAll, setSearchQuery,
  getSearchQuery, search, SearchCursor,
  abbreviationTracker, emmetCompletionSource, expandAbbreviation,
  tags, LanguageSupport, StreamLanguage,
  MODERN_FACTORIES, LEGACY_SUPPORTS,
};
