/**
 * Vendor the CodeMirror 6 editor into a TypeScript string bundle.
 *
 * The editor WebView is fully offline: `CodeMirrorWebView.tsx` inlines this
 * string into its HTML document — no CDN, no runtime network fetch.
 *
 * - Modern lezer grammars are imported statically (tree-sitter-class parsing
 *   with correct token roles per language).
 * - Legacy StreamLanguage grammars (~100) are discovered by importing every
 *   `@codemirror/legacy-modes/mode/*.js` in Node and keeping exports that
 *   quack like a parser (`token` function). The entry is generated so the
 *   registry never drifts from the installed package.
 * - Emmet abbreviation tracking + completions included (HTML-family modes).
 *
 * Usage: `npm run vendor:editor` (run after `npm install`).
 */
import { readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const require = createRequire(join(root, "package.json"));

const MODERN = [
  ["javascript", "@codemirror/lang-javascript", "javascript"],
  ["python", "@codemirror/lang-python", "python"],
  ["java", "@codemirror/lang-java", "java"],
  ["cpp", "@codemirror/lang-cpp", "cpp"],
  ["go", "@codemirror/lang-go", "go"],
  ["rust", "@codemirror/lang-rust", "rust"],
  ["php", "@codemirror/lang-php", "php"],
  ["sql", "@codemirror/lang-sql", "sql"],
  ["html", "@codemirror/lang-html", "html"],
  ["css", "@codemirror/lang-css", "css"],
  ["json", "@codemirror/lang-json", "json"],
  ["markdown", "@codemirror/lang-markdown", "markdown"],
  ["xml", "@codemirror/lang-xml", "xml"],
  ["yaml", "@codemirror/lang-yaml", "yaml"],
  ["vue", "@codemirror/lang-vue", "vue"],
  ["angular", "@codemirror/lang-angular", "angular"],
  ["sass", "@codemirror/lang-sass", "sass"],
  ["less", "@codemirror/lang-less", "less"],
  ["jinja", "@codemirror/lang-jinja", "jinja"],
  ["liquid", "@codemirror/lang-liquid", "liquid"],
  ["wast", "@codemirror/lang-wast", "wast"],
];

async function discoverLegacy() {
  const dir = join(root, "node_modules", "@codemirror", "legacy-modes", "mode");
  const files = readdirSync(dir)
    .filter((name) => name.endsWith(".js"))
    .sort();
  const found = [];
  for (const file of files) {
    const url = pathToFileURL(join(dir, file)).href;
    let mod;
    try {
      mod = await import(url);
    } catch (error) {
      console.warn(`skip legacy mode ${file}: ${error.message}`);
      continue;
    }
    for (const [exportName, value] of Object.entries(mod)) {
      if (
        value &&
        (typeof value === "object" || typeof value === "function") &&
        typeof value.token === "function"
      ) {
        found.push({ exportName, file, callFactory: false });
        continue;
      }
      // CodeMirror-5-style mode factories (asn1, mkCSS, ...): instantiate
      // once with empty config; pure parser builders, safe to call.
      if (typeof value === "function") {
        try {
          const parser = value({});
          if (parser && typeof parser.token === "function") {
            found.push({ exportName, file, callFactory: true });
          }
        } catch {
          // Factories needing real config are skipped, not faked.
        }
      }
    }
  }
  return found;
}

const legacy = await discoverLegacy();
console.log(`legacy parsers discovered: ${legacy.length}`);

const legacyImports = legacy
  .map(({ exportName, file }, index) => `import { ${exportName} as legacy${index} } from "@codemirror/legacy-modes/mode/${file.replace(/\.js$/, "")}";`)
  .join("\n");
const legacyRegistry = legacy
  .map(({ exportName, callFactory }, index) =>
    callFactory
      ? `  ${JSON.stringify(exportName)}: StreamLanguage.define(legacy${index}({})),`
      : `  ${JSON.stringify(exportName)}: StreamLanguage.define(legacy${index}),`,
  )
  .join("\n");

const modernImports = MODERN.map(
  ([key, pkg, fn]) => `import { ${fn} as modern_${key} } from "${pkg}";`,
).join("\n");
const modernRegistry = MODERN.map(
  ([key]) => `  ${JSON.stringify(key)}: modern_${key},`,
).join("\n");

const entry = `// GENERATED by scripts/vendor-cm.mjs — do not edit by hand.
import { EditorState, Compartment, Prec } from "@codemirror/state";
import {
  EditorView, keymap, lineNumbers, highlightActiveLineGutter,
  highlightSpecialChars, drawSelection, dropCursor, rectangularSelection,
  crosshairCursor, highlightActiveLine,
} from "@codemirror/view";
import {
  defaultKeymap, history, historyKeymap, indentMore, indentLess,
  undo, redo,
} from "@codemirror/commands";
import {
  foldGutter, foldAll, unfoldAll, foldEffect, foldKeymap,
  syntaxHighlighting, HighlightStyle, StreamLanguage, LanguageSupport,
  defaultHighlightStyle, indentOnInput,
} from "@codemirror/language";
import {
  autocompletion, closeBrackets, closeBracketsKeymap, acceptCompletion,
  completionKeymap, closeCompletion, completeAnyWord, startCompletion,
} from "@codemirror/autocomplete";
import {
  SearchQuery, findNext, findPrevious, selectNextOccurrence,
  selectSelectionMatches, replaceNext, replaceAll, setSearchQuery,
  getSearchQuery, search, SearchCursor,
} from "@codemirror/search";
import {
  abbreviationTracker, emmetCompletionSource, expandAbbreviation,
} from "@emmetio/codemirror6-plugin";
import { tags } from "@lezer/highlight";
${modernImports}
${legacyImports}

const MODERN_FACTORIES = {
${modernRegistry}
};

const LEGACY_SUPPORTS = {
${legacyRegistry}
};

export const AjiroCM = {
  EditorState, EditorView, Compartment, Prec,
  keymap, lineNumbers, highlightActiveLineGutter, highlightSpecialChars,
  drawSelection, dropCursor, rectangularSelection, crosshairCursor,
  highlightActiveLine, defaultKeymap, history, historyKeymap, indentOnInput,
  indentMore, indentLess, undo, redo, foldGutter, foldAll, unfoldAll, foldEffect, foldKeymap,
  syntaxHighlighting, HighlightStyle, defaultHighlightStyle,
  autocompletion, closeBrackets, closeBracketsKeymap, acceptCompletion,
  completionKeymap, closeCompletion, completeAnyWord, startCompletion,
  SearchQuery, findNext, findPrevious, selectNextOccurrence,
  selectSelectionMatches, replaceNext, replaceAll, setSearchQuery,
  getSearchQuery, search, SearchCursor,
  abbreviationTracker, emmetCompletionSource, expandAbbreviation,
  tags, LanguageSupport, StreamLanguage,
  MODERN_FACTORIES, LEGACY_SUPPORTS,
};
`;

const entryPath = join(root, "scripts", "cm-entry.gen.mjs");
writeFileSync(entryPath, entry);

const { buildSync } = require("esbuild");
const out = buildSync({
  bundle: true,
  entryPoints: [entryPath],
  format: "iife",
  globalName: "AjiroCM",
  minify: true,
  sourcemap: false,
  target: "es2020",
  write: false,
});
const bundled = out.outputFiles[0].text;
const keyList = [...new Set([...MODERN.map(([key]) => key), ...legacy.map((entry) => entry.exportName)])].sort();

const tsOut = `/**
 * GENERATED — do not edit by hand. Run \`npm run vendor:editor\`.
 * CodeMirror 6 offline bundle (core + modern grammars + legacy grammars +
 * autocomplete + search + emmet). No CDN, no runtime network fetch.
 */
export const CM_BUNDLE_JS = ${JSON.stringify(bundled)};
/** Registry keys available inside the bundle (modern + legacy). */
export const CM_MODE_KEYS: readonly string[] = ${JSON.stringify(keyList)};
`;
writeFileSync(join(root, "src", "editor", "cmBundle.ts"), tsOut);
console.log("editor vendor bundle written: src/editor/cmBundle.ts");
console.log(`  bundle: ${(bundled.length / 1024).toFixed(1)} KiB`);
console.log(`  mode keys: ${keyList.length}`);
